MisPerris2/MisPerris2/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cuentas/', include('cuentas.urls')),
    url(r'^formularioAdopcion/', include('adopcion.urls')),
    url(r'^about/$', views.about),
    url(r'^Home/$', views.Home, name="Home"),
    url(r'^$', views.homepage, name="homepage"),
    #url(r'^', include('django.contrib.auth.urls')),
    #url(r'^oauth/', include('social_django.urls',namespace="social")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



#cada vez se configura algo de la tabla o BD
#python manage.py makemigrations
#pythons manage.py migrate

#guardar en git
#git commit -a -m "nombre commit"
#git push -u origin master

MisPerris2/adopcion/urls.py
from django.conf.urls import url
from . import views

app_name='adopcion'

urlpatterns = [
    url(r'^adoptadosList/$', views.Formulario_adopcion_Listar, name="adoptadosListar"),
    url(r'^adoptadosCreate/$', views.Formulario_adopcion_Crear, name="adoptadosCrear"),

    url(r'^rescatadosList/$', views.Formulario_rescatados_Listar, name="rescatadosListar"),
    #url(r'(?P<correo>[\w-]+)/',views.Formulario_detalles, name="Detalle"),
]

MisPerris2/cuentas/urls.py
from django.conf.urls import url, include
from . import views

app_name ='cuentas'

urlpatterns = [
    url(r'^oauth/', include('social_django.urls', namespace="social")),
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
   
]

MisPerris2/adopcion/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class FormularioAdopcion(models.Model):
    REGION_CHOICES = (
        ('Tarapaca','Tarapaca'),
        ('Antofagasta','Antofagasta'),
        ('Atacama','Atacama'),
        ('Coquimbo','Coquimbo'),
        ('Valparaiso','Valparaiso'),
        ('O´Higgins','O´Higgins'),
        ('Maule','Maule'),
        ('Concepcion','Concepcion'),
        ('Araucania','Araucania'),
        ('Los Lagos','Los Lagos'),
        ('Aysén','Aysén'),
        ('Magallanes','Magallanes'),
        ('Metropolitana','Metropolitana'),
        ('Los Rios','Los Rios'),
        ('Arica','Arica'),
        ('Ñuble','Ñuble'),
    )
    CIUDAD_CHOICES = (
        ('Iquique','Iquique'),
        ('Antofagasta','Antofagasta'),
        ('Copiapo','Copiapo'),
        ('Coquimbo','Coquimbo'),
        ('Valparaiso','Valparaiso'),
        ('Rancagua','Rancagua'),
        ('Talca','Talca'),
        ('Concepcion','Concepcion'),
        ('Temuco','Temuco'),
        ('Puerto Montt','Puerto Montt'),
        ('Coyhiaique','Coyhiaique'),
        ('Punta Arenas','Punta Arenas'),
        ('Santiago','Santiago'),
        ('Valdivia','Valdivia'),
        ('Arica','Arica'),
        ('Chillán','Chillán'),
    )

    VIVIENDA_CHOICES = (
        ('Casa patio grande','Casa patio grande'),
        ('Casa patio pequeño','Casa patio pequeño'),
        ('Casa sin patio','Casa sin patio'),
        ('Departamento','Departamento'),
    )

    rut = models.CharField(max_length=12, help_text="Ej: 12.123.123-1" , unique=True)
    correo = models.CharField(max_length=100)
    nombre = models.CharField(max_length=60, help_text="Nombre Completo")
    fechaNac = models.DateTimeField(default=timezone.now)
    region = models.CharField(max_length=60, choices = REGION_CHOICES ,help_text="region")
    ciudad = models.CharField(max_length=60, choices = CIUDAD_CHOICES , help_text="ciudad")
    tipoVivienda = models.CharField(max_length=60, choices = VIVIENDA_CHOICES , help_text="vivienda") 
    autor = models.ForeignKey(User,on_delete=models.CASCADE,default=None)

    def __str__(self):
        return self.rut

class FormularioRescatado(models.Model):

    ESTADO_CHOICES = (
        ('Rescatado','Rescatado'),
        ('Disponible','Disponible'),
        ('Adoptado','Adoptado'),
    )

    fotografia = models.ImageField(default='default.png', blank=True)
    nombre = models.CharField(max_length=50)
    razaPredominante = models.CharField(max_length=50)
    descripcion = models.TextField()
    estado = models.CharField(max_length=50, choices = ESTADO_CHOICES ,help_text="Estado")

MisPerris2/cuentas/models.py
from django.db import models

# Create your models here.

MisPerris2/adopcion/forms.py
from django import forms
from . import models

class CrearAdopcion(forms.ModelForm):
    class Meta:
        model= models.FormularioAdopcion
        fields=['rut','correo','nombre','fechaNac','region','ciudad','tipoVivienda']

MisPerris2/MisPerris2/views.py
from django.http import HttpResponse 
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

def homepage(request):
    #return HttpResponse('homepage')
    return render(request,'homepage.html') 
    
@login_required(login_url="/cuentas/login/")
def Home(request):
    #return HttpResponse('Home')
    return render(request,'Home.html') 

def about (request):
    #return HttpResponse('about')
    return render(request,'about.html')

MisPerris2/adopcion/views.py
from django.shortcuts import render, redirect
from .models import FormularioAdopcion, FormularioRescatado
from django.contrib.auth.decorators import login_required
from . import forms

@login_required(login_url="/cuentas/login/")
def Formulario_adopcion_Listar(request):
    FormAdopAll = FormularioAdopcion.objects.all().order_by('nombre')
    return render(request,'adopcion/Formulario_adopcion_listar.html', {'FormAdopAll':FormAdopAll})

@login_required(login_url="/cuentas/login/")
def Formulario_rescatados_Listar(request):
    FormResAll = FormularioRescatado.objects.all().order_by('nombre')
    #FormResAll = FormularioRescatado.filter(nombre=request.nombre)
    return render(request,'adopcion/Rescate_listar.html', {'FormResAll':FormResAll})

@login_required(login_url="/cuentas/login/")
def Formulario_adopcion_Crear(request):
    if request.method=='POST':
        form=forms.CrearAdopcion(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.autor = request.user
            #intance.FormularioAdopcion.nombre=request.nombre; iguala la variable bd a la variable html
            instance.save()
            return redirect('Home')


    else:
        form = forms.CrearAdopcion()
    
    return render(request,'adopcion/adopcion_crear.html',{'form':form})

MisPerris2/cuentas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log the user in
            login(request, user)
            return redirect('homepage')
    else:
        form = UserCreationForm()
    return render(request, 'cuentas/signup.html', {'form':form})

def login_view(request):
    if request.method =='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('Home')
    else:
        form = AuthenticationForm()
    return render(request,'cuentas/login.html', {'form':form})

def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('homepage')

def index(request):
    return render(request, 'cuentas/login.html')

MisPerris2/adopcion/templates/adopcion/Formulario_adopcion_listar.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Formulario</title>
        <link rel="stylesheet" href="{% static 'estilos.css' %}">
    </head>
    <Body>
        <H1><a href="{% url 'adopcion:adoptadosListar' %}">Listar</a></H1>
        <h1>Formulario Adopcion Listar</h1>
        <div class="FormAdopAll">
                {% for FormularioAdopcion in FormAdopAll %} <!--le da a variable html variable de la bd -->
            <div class="FormularioAdopcion">
                <table>
                        <tr>
                                <th>id</th>
                                <th>rut</th>
                                <th>nombre</th>
                                <th>Fecha Nacimiento</th>
                                <th>correo</th>
                                <th>region</th>
                                <th>ciudad</th>
                                <th>Tipo Vivienda</th>
                        </tr>
                    <tr>
                        <td>{{FormularioAdopcion.id}}</td>
                        <td>{{FormularioAdopcion.rut}}</td>
                        <td>{{FormularioAdopcion.nombre}}</td>
                        <td>{{FormularioAdopcion.fechaNac}}</td>
                        <td>{{FormularioAdopcion.correo}}</td>
                        <td>{{FormularioAdopcion.region}}</td>
                        <td>{{FormularioAdopcion.ciudad}}</td>
                        <td>{{FormularioAdopcion.tipoVivienda}}</td>
                    </tr>
                <table>
            </div>
                {% endfor  %}
            </div>
    </Body>
</html>

MisPerris2/adopcion/templates/adopcion/Rescate_listar.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Formulario</title>
        <link rel="stylesheet" href="{% static 'estilos.css' %}">
    </head>
    <Body>
        <H1><a href="{% url 'adopcion:rescatadosListar' %}">Listar</a></H1>
        <h1>Formulario Adopcion Listar</h1>
        <button><a href="{% url 'homepage' %}">Inicio</a></button>
        <div class="FormAdopAll">
                {% for FormularioRescatados in FormResAll %} <!--le da a variable html variable de la bd -->
            <div class="FormularioRescatados">
                <table>
                        <tr>
                                <th>foto</th>
                                <th>nombre</th>
                                <th>raza</th>
                                <th>descripcion</th>
                                <th>estado</th>
                        </tr>
                    <tr>
                        <td><img src="{{FormularioRescatados.fotografia.url}}" height=500></td>
                        <td>{{FormularioRescatados.nombre}}</td><br>
                        <td>{{FormularioRescatados.razaPredominante}}</td>
                        <td>{{FormularioRescatados.descripcion}}</td>
                        <td>{{FormularioRescatados.estado}}</td>
                    </tr>
                <table>
            </div>
                {% endfor  %}
            </div>
    </Body>
</html>

MisPerris2/adopcion/templates/adopcion/adopcion_crear.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Formulario</title>
        <link rel="stylesheet" href="{% static 'estilos.css' %}">
    </head>
    <Body>
        <div class="crear-adopcion">
            <h2>Crear adopcion</h2>
            <form class="site.form" action="{% url 'adopcion:adoptadosCrear' %}" method="POST">
                {%csrf_token%}
                {{form}}
                <input type="submit" value="Crear">
            </form>


        </div>
    </Body>
</html>

MisPerris2/cuentas/templates/cuentas/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <style type="text/css">
        h1{text-align: center;}
        body{background : #6dccaa;}
        #loginSocial{color: blue; font-size: "4";}
        #btnGoogle{color: white;background-color: red; height: 50px;}
        #btnGithub{color: white;background-color: black;height: 50px;}
        #btnFacebook{color: white;background-color: blue;height: 50px;}
        #btnInstagram{color: white;background-color: #8a3ab9;height: 50px;}
    </style>
</head>
<body>
    <h1>Login</h1>
    
    <form  id="login-perris" class="site-form" action="{% url 'cuentas:login' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">

    </form>
    <p id="loginSocial">Login Social</p>

    <a href="{% url 'cuentas:social:begin' 'github' %}">
        <button id="btnGithub" type="button" name="button">Github</button>
    </a>
    <a href="{% url 'cuentas:social:begin' 'google-oauth2' %}">
        <button id="btnGoogle" type="button" name="button">Google</button>
    </a>
    <a href="{% url 'cuentas:social:begin' 'facebook' %}">
        <button id="btnFacebook" type="button" name="button">Facebook</button>
    </a>
    <a href="{% url 'cuentas:social:begin' 'instagream' %}">
        <button id="btnInstagram" type="button" name="button">Instagram</button>
    </a>
    <br>
    <br>
    <br>
    <br>
    <button id="btnInicio"><a href="{% url 'homepage' %}">Inicio</a></button>
</body>
</html>

MisPerris2/cuentas/templates/cuentas/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Signup</title>
</head>
<body>
    <h1>Signup</h1>
    <form  class="site-form" action="/cuentas/signup/" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="registrar">

    </form>
    <button><a href="{% url 'homepage' %}">Inicio</a></button>
</body>
</html>

MisPerris2/templates/Home.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="es">
  <head>
      <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'estilos.css' %}"  media="screen,projection"/>
      <title>Mis Perris </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
      
      <header>
      <center>
      <div class="inicio" id="inicio">
           <img class="responsive-img" src="{% static 'image/logo.png' %}" alt="LogoMisPerris" width = "80%">
      </div>
      </center>
      </header>

<nav>
  <div class="nav-wrapper">
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="left hide-on-med-and-down">
      <li><a href="#inicio">Inicio</a></li>
      <li><a href="#quienessomos">Quienes somos</a></li>
      <li><a href="#servicios">Servicios</a></li>
      <li><a href="#contactanos">Contáctanos</a></li>
      <li><a href="{% url 'adopcion:adoptadosCrear' %}">Formulario adopción</a></li>
      <li><a href="http://127.0.0.1:8000/admin/login/?next=/admin/">SuperUser</a></li>
      <li><a href="{% url 'adopcion:rescatadosListar' %}">Perritos</a></li>
      <li>
          <form class="logout-link" action="{% url 'cuentas:logout'%}" method="POST">
              {%csrf_token%}
              <button class="waves-effect waves-light btn" type="submit">Cerrar sesion</button>
          </form>
      </li>
    </ul>
</nav>
</div>

    <ul class="sidenav" id="mobile-demo" >
      <li><a href="#inicio">Inicio</a></li>
      <li><a href="#quienessomos">Quienes somos</a></li>
      <li><a href="#servicios">Servicios</a></li>
      <li><a href="#contactanos">Contáctanos</a></li>
      <li><a href="{% url 'adopcion:adoptadosCrear' %}">Formulario adopción</a></li>
      <li><a href="http://127.0.0.1:8000/admin/login/?next=/admin/">SuperUser</a></li>
      <li><a href="{% url 'adopcion:rescatadosListar' %}">Perritos</a></li>
      <li>
          <form class="logout-link" action="{% url 'cuentas:logout'%}" method="POST">
              {%csrf_token%}
              <button class="waves-effect waves-light btn" type="submit">Cerrar sesion</button>
          </form>
      </li>
    </ul>
      
      <div id="espacio">
              <div id="carousel" class="carousel carousel-slider">
                  <a class="carousel-item" href="#one!"><img id="ImagenCarrusel" src="{% static 'adoptados/Apolo.jpg' %}"></a>
                  <a class="carousel-item" href="#two!"><img id="ImagenCarrusel" src="{% static 'adoptados/Duque.jpg' %}"></a>
                  <a class="carousel-item" href="#three!"><img id="ImagenCarrusel" src="{% static 'adoptados/Tom.jpg' %}"></a>
                  <a class="carousel-item" href="#four!"><img id="ImagenCarrusel" src="{% static 'image/4.jpg' %}"></a>
                  <a class="carousel-item" href="#five!"><img id="ImagenCarrusel" src="{% static 'image/5.jpg' %}"></a>
              </div>
              
              
              <center>
              <div class="redesSociales" id="contactanos">
                  <div class="circle button">
                      <a href="https://es-la.facebook.com/" ><img src= "{% static 'image/facebook.png' %}" width="10%"></a>
                      <a href="https://plus.google.com/discover?hl=es" ><img src= "{% static 'image/google+.png' %}" width="10%"></a>
                      <a href="https://www.instagram.com/?hl=es-la" ><img src= "{% static 'image/instagram.png' %}" width="10%"></a>
                      <a href="https://accounts.google.com/" ><img src= "{% static 'image/email.png' %}" width="10%"></a>
                  </div>
              </div>
              </center>
              </div>
              

      <section class="section1" id="quienessomos">
      
      <h2 align=right><font face=tahoma ><b>RESCATE</b></font></h2>
      <h4 align=right><font face=tahoma color=grey >ETAPA UNO</font></h4>
      <hr size=20 width=10% align=right>
      <br>
      <p align=right><font size=6 font=tahoma>Rescatamos perros en situación de peligro y/o abandono.Los rehabilitamos y los preparamos para buscarles un hogar.</font></p>
      <img src= "{% static 'image/rescate.jpg' %}" alt="Rescate" width="50%" align= "right">
      
      </section>
      
      <img src= "{% static 'image/crowfunding.jpg' %}" alt="crowfunding" width="50%" align= "left">

      <section class="section2" id="servicios">

      <h2 align=left><font face=tahoma ><b>CROWFUNDING</b></font></h2>
      <h4 align=left><font face=tahoma color=grey >FINANCIAMIENTO</font></h4>
      <hr size=20 width=10% align=left>
      <br>
      <p align=left><font size=6 font=tahoma>Sigue nuestras redes sociales para informarte acerca de las diversas campañas y actividades que realizamos para obtener financiamiento para seguir ayudando.</font></p>
      <br>
              <div class="button" id="button1">	
              <a href="campañas.html" ><font color="black" face="tahoma"><b>CAMPAÑAS</b></font></a>
              </div>
      </section>
      
      <section class="section3">
      

      </section>
      
      <footer>
      
      <h4> Desarrollo Web y Mobile </h4>
      
      </footer>
      
      
      
    
      <script type="text/javascript" src="{% static 'materialize.min.js' %}""></script>
      <script> M.AutoInit(); </script>
      <script>   
              $('.carousel.carousel-slider').carousel({
              fullWidth: true
              }); 
      </script>
      
  </body>
</html>

MisPerris2/templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
    </head>
    <Body>
        <h1>About perra</h1>
    </Body>
</html>

MisPerris2/templates/homepage.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="es">
  <head>
      <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'estilos.css' %}"  media="screen,projection"/>
      <title>Mis Perris </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
      
      <header>
      <center>
      <div class="inicio" id="inicio">
           <img class="responsive-img" src="{% static 'image/logo.png' %}" alt="LogoMisPerris" width = "80%">
      </div>
      </center>
      </header>
      
<nav>
  <div class="nav-wrapper">
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="left hide-on-med-and-down">
      <li><a href="#inicio">Inicio</a></li>
      <li><a href="#quienessomos">Quienes somos</a></li>
      <li><a href="#servicios">Servicios</a></li>
      <li><a href="#contactanos">Contáctanos</a></li>
      <li><a href="{% url 'adopcion:adoptadosCrear' %}">Formulario adopción</a></li>
      <li><a href="http://127.0.0.1:8000/admin/login/?next=/admin/">SuperUser</a></li>
      <li><a href="{% url 'adopcion:rescatadosListar' %}">Perritos</a></li>
      <li><a href="{% url 'cuentas:signup' %}">Registrarse</a></li>
      <li><a href="{% url 'cuentas:login' %}">Iniciar sesion</a></li>
      <li>
          <form class="logout-link" action="{% url 'cuentas:logout'%}" method="POST">
              {%csrf_token%}
              <button class="waves-effect waves-light btn" type="submit">Cerrar sesion</button>
          </form>
      </li>
    </ul>
  </div>
</nav>

    <ul class="sidenav" id="mobile-demo" >
      <li><a href="#inicio">Inicio</a></li>
      <li><a href="#quienessomos">Quienes somos</a></li>
      <li><a href="#servicios">Servicios</a></li>
      <li><a href="#contactanos">Contáctanos</a></li>
      <li><a href="{% url 'adopcion:adoptadosCrear' %}">Formulario adopción</a></li>
      <li><a href="http://127.0.0.1:8000/admin/login/?next=/admin/">SuperUser</a></li>
      <li><a href="{% url 'cuentas:signup' %}">Perritos</a></li>
      <li><a href="{% url 'cuentas:signup' %}">Registrarse</a></li>
      <li><a href="{% url 'cuentas:login' %}">Iniciar sesion</a></li>
      <li>
          <form class="logout-link" action="{% url 'cuentas:logout'%}" method="POST">
              {%csrf_token%}
              <button class="waves-effect waves-light btn" type="submit">Cerrar sesion</button>
          </form>
      </li>
    </ul>
      
      <div id="espacio">
              <div id="carousel" class="carousel carousel-slider">
                  <a class="carousel-item" href="#one!"><img id="ImagenCarrusel" src="{% static 'adoptados/Apolo.jpg' %}"></a>
                  <a class="carousel-item" href="#two!"><img id="ImagenCarrusel" src="{% static 'adoptados/Duque.jpg' %}"></a>
                  <a class="carousel-item" href="#three!"><img id="ImagenCarrusel" src="{% static 'adoptados/Tom.jpg' %}"></a>
                  <a class="carousel-item" href="#four!"><img id="ImagenCarrusel" src="{% static 'image/4.jpg' %}"></a>
                  <a class="carousel-item" href="#five!"><img id="ImagenCarrusel" src="{% static 'image/5.jpg' %}"></a>
              </div>
              
              
              <center>
              <div class="redesSociales" id="contactanos">
                  <div class="circle button">
                      <a href="https://es-la.facebook.com/" ><img src= "{% static 'image/facebook.png' %}" width="10%"></a>
                      <a href="https://plus.google.com/discover?hl=es" ><img src= "{% static 'image/google+.png' %}" width="10%"></a>
                      <a href="https://www.instagram.com/?hl=es-la" ><img src= "{% static 'image/instagram.png' %}" width="10%"></a>
                      <a href="https://accounts.google.com/" ><img src= "{% static 'image/email.png' %}" width="10%"></a>
                  </div>
              </div>
              </center>
              </div>
              

      <section class="section1" id="quienessomos">
      
      <h2 align=right><font face=tahoma ><b>RESCATE</b></font></h2>
      <h4 align=right><font face=tahoma color=grey >ETAPA UNO</font></h4>
      <hr size=20 width=10% align=right>
      <br>
      <p align=right><font size=6 font=tahoma>Rescatamos perros en situación de peligro y/o abandono.Los rehabilitamos y los preparamos para buscarles un hogar.</font></p>
      <img src= "{% static 'image/rescate.jpg' %}" alt="Rescate" width="50%" align= "right">
      
      </section>
      
      <img src= "{% static 'image/crowfunding.jpg' %}" alt="crowfunding" width="50%" align= "left">

      <section class="section2" id="servicios">

      <h2 align=left><font face=tahoma ><b>CROWFUNDING</b></font></h2>
      <h4 align=left><font face=tahoma color=grey >FINANCIAMIENTO</font></h4>
      <hr size=20 width=10% align=left>
      <br>
      <p align=left><font size=6 font=tahoma>Sigue nuestras redes sociales para informarte acerca de las diversas campañas y actividades que realizamos para obtener financiamiento para seguir ayudando.</font></p>
      <br>
              <div class="button" id="button1">	
              <a href="campañas.html" ><font color="black" face="tahoma"><b>CAMPAÑAS</b></font></a>
              </div>
      </section>
      
      <section class="section3">
      

      </section>
      
      <footer>
      
      <h4> Desarrollo Web y Mobile </h4>
      
      </footer>
      
      
      
    
      <script type="text/javascript" src="{% static 'materialize.min.js' %}""></script>
      <script> M.AutoInit(); </script>
      <script>   
              $('.carousel.carousel-slider').carousel({
              fullWidth: true
              }); 
      </script>
      
  </body>
</html>